language: python

python:
  - "3.6"
  - "3.7-dev"


script:
- pytest --cov=./

install: pip install codecov pytest-asyncio pytest-cov

env:
  - CODECOV_TOKEN="9f861ef0-f2c7-40fc-bb72-662d403d19a8"

after_success:
  - codecov


